services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: jshan
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
#  ideally, i would want to create different databases for each microservice.
#  meaning that I would have to add "postgres-fraud" for "fraud" service
#  however, since I'm running this in local env. and running out of memories, I'm sticking with the one database
#  and separate each microservice with separate schema. (i.e. /customer, /fraud, /..
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: